// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkJyYwKYjfLR77cQ4hupNqc6Zq4esudwM',
    appId: '1:258527902135:web:a625bb7075f88a50135032',
    messagingSenderId: '258527902135',
    projectId: 'chatapp-f432f',
    authDomain: 'chatapp-f432f.firebaseapp.com',
    storageBucket: 'chatapp-f432f.appspot.com',
    measurementId: 'G-QTXXPDGLBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ZVF49X_LyBg3vqtSFdbTH8RmfT3P04s',
    appId: '1:258527902135:android:e639d522570eae20135032',
    messagingSenderId: '258527902135',
    projectId: 'chatapp-f432f',
    storageBucket: 'chatapp-f432f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpS1dPgttKXpVOO_cYgfcVSrdtIG5imwA',
    appId: '1:258527902135:ios:0fca52e02aba262e135032',
    messagingSenderId: '258527902135',
    projectId: 'chatapp-f432f',
    storageBucket: 'chatapp-f432f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpS1dPgttKXpVOO_cYgfcVSrdtIG5imwA',
    appId: '1:258527902135:ios:902e2edb2493d678135032',
    messagingSenderId: '258527902135',
    projectId: 'chatapp-f432f',
    storageBucket: 'chatapp-f432f.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
